Added tapenade checks
mdolab/.github pull request #19
Opened 2021-07-23 03:31 UTC by nwu63

## Purpose
Closes #15. Only 3.16 is used currently since older versions are not available online.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

2021-07-23 11:00 UTC, eirikurj commented
Older versions of tapenade do exist in their gitlab repo https://gitlab.inria.fr/tapenade/tapenade
Cloning the repo and checking out the correct tag to recover the older versions should work. For us, the `tap-3.10-5363` tag should be what we use. 
Should we not try to first integrate the older tapenade version, so we can add tests to the current committed code in our repos?

2021-07-23 12:31 UTC, nwu63 commented
I tried this locally but could not get the older code to run, I got the error
```
Error: Could not find or load main class topLevel.Tapenade
Caused by: java.lang.ClassNotFoundException: topLevel.Tapenade
```
despite setting $TAPENADE_HOME and $JAVA_HOME. So I suspect that the sources have to be built (which I then tried to do following instructions [here](https://gitlab.inria.fr/tapenade/tapenade/-/tree/dc98a2747515d83b91d957f4ad1364077ae37366/distrib) but did not get that to work, possibly due to incompatible Java versions.

At this point, I feel building from source is a bit too much hassle which is why I opted to just work with the new version. If they are okay with us re-distributing our own 3.10 binaries then we could just use that instead and it should work as done with 3.16 here.

2021-07-26 13:18 UTC, eirikurj commented
Since tapenade 3.10 is effectively available, I think it's probably ok to self-host the 3.10 tar and use or our testing.

2021-07-26 14:21 UTC, nwu63 commented
I have updated the PR with support for 3.10. Since we can't test this there will probably be things to fix once this is merged and we use this on a PR. I will probably just directly push to master to fix that then.

2021-07-26 14:32 UTC, bernardopacini requested changes
Overall this looks good to me, but I added a few notes that might be issues when we implement this.

I have two additional questions as well:

1) Should we place this in a file that is separate from the style check? I agree it does not belong with the build or test scripts, but it seems like it may warrant a separate file as it is not exactly a style check.

2) I find that Tapenade uses Docker when running on both my Mac and Ubuntu machines. I am not sure if Tapenade can run without it. If it needs Docker while running, will this be an issue for us?

2021-07-26 14:46 UTC, nwu63 commented on azure/azure_style.yaml
> +            wget http://www-sop.inria.fr/ecuador/tapenade/distrib/tapenade_3.16.tar
I just tried this in Docker and it seems to work, we will have to try this on a PR I think to see.

2021-07-26 14:47 UTC, nwu63 commented on azure/azure_style.yaml
> +          jdkSourceOption: "PreInstalled"
Yep according to the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) the environment variable is automatically set.

2021-07-26 14:48 UTC, nwu63 commented
>     1. Should we place this in a file that is separate from the style check? I agree it does not belong with the build or test scripts, but it seems like it may warrant a separate file as it is not exactly a style check.

Good point, I will move this to a separate check then. Can you remind me what exactly does this do? Obviously the file structure will be different in the `.github` repo but does this affect anything running these checks? Just the heading on the individual jobs or something?

>     2. I find that Tapenade uses Docker when running on both my Mac and Ubuntu machines. I am not sure if Tapenade can run without it. If it needs Docker while running, will this be an issue for us?

Docker is available on all these machines so I think we are okay here, again won't know until we try it.

2021-07-26 15:28 UTC, bernardopacini commented
> > ```
> > 1. Should we place this in a file that is separate from the style check? I agree it does not belong with the build or test scripts, but it seems like it may warrant a separate file as it is not exactly a style check.
> > ```
> 
> 
> Good point, I will move this to a separate check then. Can you remind me what exactly does this do? Obviously the file structure will be different in the `.github` repo but does this affect anything running these checks? Just the heading on the individual jobs or something?
> 
> 

Do you mean what exactly making a new file does? It will create a new block on Azure, just like the style and build / test ones. Other than that, it will look just like the others.

Another option is to simply make the "Style" name more general, such as "Code Consistency" or something along those lines and avoid a new file.

2021-07-26 21:57 UTC, bernardopacini commented
These updates look good to me. I am not sure if in the long run we have any other checks that we can combine into the same file with Tapenade, in which case the `Azure_Tapenade` file might need a new name, but at least for what we need now this looks good to me.

2021-07-26 21:57 UTC, bernardopacini approved these changes

2021-07-26 22:18 UTC, merged